title: Anderson Mesquita França
description: Ciência de Dados, Inteligência Artificial e Saúde Pública

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

locale: pt-BR
markdown: kramdown

paginate: false
search: false
breadcrumbs: false

minimal_mistakes_skin: default

author:
  name: Anderson Mesquita França
  avatar:
  bio: Cientista de Dados e pesquisador em Saúde Pública
  location         : "Somewhere"
  email            : contato@andersonfranca.Mesquita
links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:contato@andersonfranca.me"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "andersonfranca.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"